# Import layers

In [1]:

import time
import numpy as np
import seaborn as sns
import sys
from pathlib import Path

In [2]:

p = Path()
LOCAL_PATH = str(p.cwd())
ROOT_PATH  = str(p.cwd().parent.parent.parent)
LAYER_PATH = str(p.cwd().parent.parent)
info = """LOCAL_PATH: '{}'
ROOT_PATH : '{}'
LAYER_PATH: '{}'
""".format(LOCAL_PATH, ROOT_PATH, LAYER_PATH)
print(info)

# add:
sys.path.append(LAYER_PATH)
sys.path.append(ROOT_PATH)

from sys_function import *

LOCAL_PATH: '/home/gheorghe/Desktop/Proiecte/master/CARN/deep_learning/loss/test'
ROOT_PATH : '/home/gheorghe/Desktop/Proiecte/master/CARN'
LAYER_PATH: '/home/gheorghe/Desktop/Proiecte/master/CARN/deep_learning'



In [47]:

sys_remove_modules("loss", "ssim_loss")

from loss.ssim_loss import *

# Build criterion

In [56]:

criterion = SSIMLoss(1)

In [57]:

for _ in range(10000):
    pred    = torch.rand(1, 1, 3, 3)
    targets = torch.rand(1, 1, 3, 3)
    kl = criterion(pred, targets).sum()
    if (kl > 0):
        print("kl", kl)
        print(pred)
        print(targets)
    else:
        pass
        #print("zb")

kl tensor(1.4533)
tensor([[[[0.4262, 0.4171, 0.8808],
          [0.3216, 0.8350, 0.3135],
          [0.3118, 0.7439, 0.2142]]]])
tensor([[[[0.3420, 0.1129, 0.1133],
          [0.6891, 0.3672, 0.6439],
          [0.1382, 0.2491, 0.4993]]]])
kl tensor(0.7789)
tensor([[[[0.5957, 0.4272, 0.8669],
          [0.4580, 0.8714, 0.0792],
          [0.7131, 0.1613, 0.1324]]]])
tensor([[[[0.6208, 0.4727, 0.9049],
          [0.8978, 0.4318, 0.7443],
          [0.6699, 0.0925, 0.2805]]]])
kl tensor(1.4001)
tensor([[[[0.4137, 0.8779, 0.0073],
          [0.0624, 0.6356, 0.7236],
          [0.1770, 0.6890, 0.5798]]]])
tensor([[[[0.2932, 0.4546, 0.7857],
          [0.6518, 0.2939, 0.8806],
          [0.5183, 0.4083, 0.6096]]]])
kl tensor(1.7794)
tensor([[[[0.4938, 0.7181, 0.5857],
          [0.8621, 0.7521, 0.0113],
          [0.6985, 0.0883, 0.1527]]]])
tensor([[[[0.0402, 0.3145, 0.5275],
          [0.7557, 0.9923, 0.7598],
          [0.1910, 0.2257, 0.7793]]]])
kl tensor(1.0417)
tensor([[[[0.7221, 0.1

In [ ]:

log_p = torch.rand(1, 1, 3, 3)
print("log_p", log_p)

log_p = F.softmax(log_p, dim=-1)   # input
print("log_p", log_p)